### PR TITLE
Follow up PR: enable stale bot

### PR DESCRIPTION
**Pull request by grst**
Follow-up PR on #814, to discuss its behavior and eventually disable the dry-run mode.

### CODE REVIEW

**Comment by grst** [comment]
Here's the output of 'label stale issue': 
https://github.com/scverse/anndata/runs/8204846798?check_suite_focus=true

Here's the output of 'close stale issues':
https://github.com/scverse/anndata/runs/8205105299?check_suite_focus=true

I think the "label" process looks already like what we'd expect. I'm not so sure about the "close" workflow. We can only tell once the first issues are labelled as stale and 14 days have passed. I would therefore suggest to only enable the "label" process first, and activate the "close" workflow later. 

P.S.
Since the workflow has now been executed once from the main branch, it is now possible to execute it from a feature branch. So no need to merge anything until we have a final solution: 
image

**Comment by ivirshup** [comment]
@grst, sorry about the late response here. Yes, happy to enable stale.

That can be done in this PR? Or does it need to be merged?

**Comment by grst** [comment]
This needs to be merged to enable the cron-job. 

(It would be possible to manually dispatch the workflow from this PR. But this needs to be done multiple times as not all actions are performed at once due to API limits)

**Comment by ivirshup** [comment]
Alright, I'll merge in the morning tomorrow – so we're more available in case anything blows up

**Comment by grst** [comment]
It will anyway blow up at night because of the cron job 🙃

Ok, let's first run a manual dispatch tomorrow, then merge

**Comment by grst** [comment]
@ivirshup, this is what the action produced by running it once: 
https://github.com/scverse/anndata/issues?q=label%3Astale

(more will be labelled when it is run again, e.g. by the cronjob)

**Comment by ivirshup** [comment]
* Should we mark upstream issues as stale? https://github.com/scverse/anndata/issues/797
* We shouldn't mark bugs: https://github.com/scverse/anndata/issues/788

**Comment by grst** [comment]
> Should we mark upstream issues as stale? 

maybe it's a good reminder to check if the upstream issue got fixed? 

> We shouldn't mark bugs:

Actually, you asked me to do so, see https://github.com/scverse/anndata/pull/814#issuecomment-1236954096 ff. :wink:

**Comment by ivirshup** [comment]
Ahh, missed the notification for this – sorry

> maybe it's a good reminder to check if the upstream issue got fixed?

Maybe? Is the logic here just we check, comment saying it's still a problem, then the bot pings again in however many weeks?

**Comment by grst** [comment]
>  Is the logic here just we check, comment saying it's still a problem, then the bot pings again in however many weeks?

Yes, it would ping again after 60 days

**Comment by flying-sheep** [comment]
is this ready? would be great to be able to cut down on old issues

**Comment by grst** [comment]
Yes, I think so. I inspected the dry run some time ago. Maybe take another look at that one if it does what you would expect.

**Comment by grst** [comment]
It's currently configured to be very lenient. It will only label issues as stale, but not close them. 
The second part that will close them is still in "dry-run" mode and would only close issues that are stale and have the label "needs-info".

**Pull request merged**
