### PR TITLE
Export SparseDataset

### PR DESCRIPTION
**Pull request by ivirshup**
Exporting the SparseDataset class since we expose it to users anyways. Re: #326

### CODE REVIEW

**Comment by ivirshup** [comment]
But`SparseDataset` does have `shape` and `__getitem__`?

**Comment by flying-sheep** [comment]
Right, it does have that, sorry. What I meant: I don’t think exporting `SparseDataset` with its current API and in its current role is wise, as we lock ourselves down to `X` of a backed AnnData having an API that’s both too specific (tied to HDF5) and not powerful enough (isn’t a real matrix/array)

My ideal API would be:

```py
if adata.backing is not None:
    # do backed things
if scipy.sparse.issparse(adata.X):
    # do sparse things
else:
    # do dense things
```

**Comment by ivirshup** [comment]
I don't think `SparseDataset` is tied to hdf5, IIRC it works with a zarr group on the backend too. I'm not sure what you mean by "not powerful enough".

Isn't that API what we have right now?

**Comment by flying-sheep** [comment]
It’s not, as `not issubclass(SparseDataset, spmatrix)`. And in case of a backed dense matrix, we have a straight `h5py.Dataset` as `X`. If we document this as the truth, we’ll always be tied to having a `Dataset` with its full API there. I was thinking more of something like this:

**Comment by ivirshup** [comment]
> It’s not, as not issubclass(SparseDataset, spmatrix)

Ah, thought there was an `elif` in there.

Does subclassing go in reverse order of the arrows?

We definitely should not be subclassing the scipy sparse matrix types at all. This was done before and is why backed sparse arrays were broken for quite a while (pre-`0.7`). They are specialized for in memory data, and even specific memory layout, and we can't expect their methods to work on backed arrays.

On the `h5py.Dataset`, I think that has become the standard convention for backed dense arrays in the ecosystem. It's that api that make working with `zarr` and `h5py` pretty interchangeable. The `h5py.Dataset` and `zarr.Array` also increase `dask` compatibility so I think those are valuable to keep.

**Comment by ivirshup** [comment]
Regardless of what the ideal interface is here, can we agree on keeping the current type interface until `0.8`?

**Comment by flying-sheep** [comment]
Sure, but we can’t export it until we converge on something we want to support for a long time, which isn’t this.

**Comment by ivirshup** [comment]
I think we shouldn't change this before 0.8, as people use it and open issues for it. I also think exporting is pretty light weight in terms of support. There's nothing that prevents us from deprecating it. I would like to have a solution for #326, and I think the simplest solution is:

```python
if isinstance(adata.X, (spmatrix, SparseDataset)):
    # then it's sparse
```

It's not clear to me what you don't like about the current set up. Could you elaborate on that?

* What is lacking from the current implementation? What would you like to be able to do?
* What is the alternative implementation you're proposing? How would this be implemented, and how does usage change?

**Comment by flying-sheep** [comment]
Our docs represent our public, supported interface. Supporting something means we update the the type info to include the newly supported thing.

AnnData.X is documented to have type `Optional[Union[np.ndarray, sparse.spmatrix, ArrayView]]`. Supporting something else there means:

1. The class has to be public
2. We’ll support X to have that class for a long time.

By now we actually don’t really support backed mode, as we lie about `AnnData.X`’s type. To stop lying we need to define the class that can to go there that we want to support.

And that class can’t be `h5py.Dataset`, as `h5py.Dataset` has h5py specific APIs. If we add a class of our design, we have to export and document that class’s APIs.

**Comment by ivirshup** [comment]
Superseded by #765

**Pull request closed without merging**
