### PR TITLE
Fix pre-release tests

### PR DESCRIPTION
**Pull request by flying-sheep**
@ilan-gold this should unblock you

See https://github.com/scverse/anndata/issues/1434 (doesn‘t fix that one though)

### CODE REVIEW

**Review by ilan-gold — APPROVED** [review]
I'm fine with upper bounding packages.  I will take a look at the issue.  Is @ivirshup ok with upper bounding this?  I can't think of a good reason not to but he often has something up his sleeve!

**Comment by flying-sheep** [comment]
Scipy is unlikely to change their implementation to not use `copy=True`, so it’s on us to make this work.

Since it’s not a temporary bug in scipy but a change that broke us, I introduced a temporary upper bound (as opposed to a `!=1.13.0.rc1` constraint) until we have a fix.

**Comment by ivirshup** [comment]
> In an ideal world, all past anndata versions would have the same bound, but that’s impossible to do.

I believe conda-forge actually allows this

**Comment by flying-sheep** [comment]
Yeah, I was thinking about PyPI. There it would also kinda maybe be possible by yanking everything and releasing .post1 releases but I don't think that's a reasonable standard to hold ourselves to and it would force people to change their lock files

**Pull request merged**
