### PR TITLE
Fix: Dense OOC Concat With Aligned Elements Memory Issue

### PR DESCRIPTION
**Pull request by selmanozleyen**
Please see https://github.com/scverse/anndata-tutorials/pull/18#issuecomment-1751284746. This PR should fix this memory issue.

Ping: @ivirshup @flying-sheep

### CODE REVIEW

**Comment by ivirshup** [comment]
@selmanozleyen, could you make a quick demonstration of the performance benefits from this?

**Comment by selmanozleyen** [comment]
Hey, I modified the fix as it seemed like it would expand to more cases (e.g. when they are all not the same).  The changes on results can be seen from the tutorial notebook https://github.com/scverse/anndata-tutorials/pull/18/commits/b12e539cd0a73aff1e304706a24bff3684756a4c#r1349746130

**Comment by ivirshup** [comment]
From previous discussion about this, my impression was that `da.from_array(a, chunks="auto")` would use `a.chunks` as the chunks if it was defined.

I will try and take a look, but it looks to me like these changes could be coming from the use of `write_chunked`.

**Comment by selmanozleyen** [comment]
> my impression was that `da.from_array(a, chunks="auto")` would use `a.chunks` as the chunks if it was defined.
> 
> I will try and take a look, but it looks to me like these changes could be coming from the use of `write_chunked`.

I see, I initially tried that but it didn't work for some reason. If I switch to main branch the results would be the same.

**Comment by flying-sheep** [comment]
That tracks with the documentation:

> The word “auto” which acts like the above, but uses a configuration value `array.chunk-size` for the chunk size

No word of reusing the array chunks.

**Review by flying-sheep — APPROVED** [review]

**Comment by ivirshup** [comment]
@flying-sheep, shouldn't this get a release note and a test?

**Pull request merged**
