### PR TITLE
Add prettier pre-commit

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by flying-sheep** [comment]
pre-commit.ci autofix

**Comment by flying-sheep** [comment]
Huh, the changes in 65ce47ee1c732ba86c407d39070dfb93929509a5 are broken. We need to figure out what does that

**Comment by flying-sheep** [comment]
Ah, we need to use colon fences

**Review by ivirshup — COMMENTED** [review]
Looks mostly good. Can we configure to not remove the trailing commas in json lists? (so long as that's valid)

**Review by ivirshup — APPROVED** [review]
Ah nvm, looks like trailing commas are only allowed by whatever json superset also allows comments in the asv config.

**Comment by flying-sheep** [comment]
I figured it out, that bothered me as well: https://github.com/prettier/prettier/pull/10323

**Pull request merged**
