### PR TITLE
add pytest github actions

### PR DESCRIPTION
**Pull request by rcannood**
This PR adds a GitHub Actions CI for testing anndata with pytest.

Uncomment the last section if so desired :)

### CODE REVIEW

**Comment by rcannood** [comment]
Ugh. Only after creating the PR do I see that anndata is being tested by azure devops.

@ivirshup What do you think about this PR? The benefit of running it in this way is that people who make forks for the theislab/anndata repository (e.g. me) can automatically run the pytest CI.

**Comment by ivirshup** [comment]
Ha, I was wondering what was up when you sent that link before. Thanks for going through the effort of setting this up! CI is definitely pretty key to the development process.

I'm not sure I want to have multiple CI systems, just because debugging CI is never fun and I don't want to do it twice as often. I do appreciate that there's value to distributing the CI load onto forks; however, I don't think we're having CI load issues at the moment. There are some features we like in Azure like being able to see plots from tests for scanpy, being able to use custom instances for CI in the future. I am also a bit concerned with frequently [github actions has issues](https://twitter.com/githubstatus).

How useful is this to you? Would you be fine with just using the CI on this repo?

**Comment by rcannood** [comment]
I understand that the Azure CI has clean benefits for theislab.

I am definitely sufficiently happy only using this CI for my own purposes. It'll be a bit annoying to merge my any potential contributions to theislab/anndata, because I need to remove the CI before creating a PR :P

I think there may be some middle ground to this conversation. It would be possible to merge this PR; but then [disable the pytest workflow from running in this repository](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow). This way, theislab/anndata can rely on Azure CI but potential contributors can use GitHub Actions CI. 

If any issues arise that seem to be due to github actions rather than anndata itself, feel free to ping me.

What do you think? :)

**Comment by ivirshup** [comment]
Main thing I think I'm not understanding here: Why not just open a draft PR and use our CI instead of having the CI run on a fork?

**Comment by rcannood** [comment]
I understand your concern regarding having multiple CI systems running in parallel. Disabling the GitHub CI in the theislab/anndata repository would solve this issue.

I think there are benefits to using CI for non-theislab developers working on separate forks:

* CI runs as soon as they start creating commits. If they eventually decide to create a PR, the proposed changes will (/should) have passed the CI checks.
* If all potential contributors would start creating PRs to see if their code passes CI, the repository would become bloated with PRs of code that the potential contributor does not want to merge just yet.
* As a non-theislab developer, I can't actually see the output of Azure CI in a PR. If the CI fails, fixing bugs or debugging the CI would have to be done by you as opposed to the potential contributor, since they can't see the error message.

What is your opinion on this? Would you like to propose me to change something in the PR?

**Comment by rcannood** [comment]
Closing this PR

**Comment by flying-sheep** [comment]
we switched to GH actions in #1906 because it’s faster, more convenient to access for us and others, and we use it everywhere else (making fixes easier)

**Pull request closed without merging**
