### PR TITLE
Make `strings_to_categoricals` upon `.write()` optional

### PR DESCRIPTION
**Pull request by falexwolf**
To illustrate that it'd be a simple change, this PR adds the 3 lines for what @ivirshup suggested [here](https://github.com/scverse/anndata/issues/534#issuecomment-813901847) 3 years ago:

> I think I'd be fine with a keyword argument for this.

In the two issues below, @grst, @adamgayoso, @lazappi & @ljjh20 expressed that "forced" sanitization is problematic.

- https://github.com/scverse/anndata/issues/534
- https://github.com/scverse/scanpy/issues/1747

I found these issues only now but also agree that a write function should not mutate the object that's about to be written. @chaichontat made me aware.

Things turn out particularly bad for gene symbols, which should remain strings even for performance reasons and compatibility with JS. Having 30k categories in a 32k dimensional genes vector is detrimental, not beneficial.

### CODE REVIEW

**Comment by lazappi** [comment]
Just chipping in to say that while I think this would be great, it doesn't really solve https://github.com/scverse/scanpy/issues/1747 as **scanpy** functions will still cause this conversion (unless something has changed). So this helps if you are just reading/writing `AnnData` but anything that goes through **scanpy** is still likely to be converted to categoricals.

You probably knew this already but wanted to make it clear for anyone reading this later.

**Comment by falexwolf** [comment]
> Just chipping in to say that while I think this would be great

Great that you're also onboard, @lazappi!

> as scanpy functions will still cause this conversion (unless something has changed)

Yes, you're right about the Scanpy plotting functionality. But I think the issue is more pressing for anndata, given its widespread use outside of Scanpy.

**Review by ilan-gold — APPROVED** [review]

**Review by flying-sheep — APPROVED** [review]

**Comment by ilan-gold** [comment]
@flying-sheep I am disabling auto-merge.  Isaac brought up a good point about whether this should be in `settings` on zulip.  What do you think?  I think it's fine to leave this here because you might have different behavior for different datasets.  If you agree we can merge (two against one haha).

**Comment by ilan-gold** [comment]
@ivirshup your call then.

**Comment by ilan-gold** [comment]
I am fine leaving this as-is @flying-sheep so will enable auto-merge

**Comment by ilan-gold** [comment]
> I think we didn’t fully agree on if this should be an “and” or an “or” for things to go into settings.

I am comfortable with "or" here

**Comment by flying-sheep** [comment]
weird. We actually don’t document `anndata.io.write_{zarr,h5ad}` yet, and this PR didn’t add the API to `anndata.AnnData.write_{zarr,h5ad}`. I think we should fix all that.

**Pull request merged**
