### PR TITLE
(fix): correct default fill values for dask-sparse

### PR DESCRIPTION
**Pull request by ilan-gold**
- [x] Noticed in #1247
- [x] Tests added
- [x] Release note added (or unnecessary)

### CODE REVIEW

**Review by flying-sheep — APPROVED** [review]
Doesn’t look like we use the test “is a sparse matrix/array or a Dask array containing a sparse matrix/array” anywhere else so I’m not suggesting to make this a helper in this PR yet

**Comment by flying-sheep** [comment]
Dask sparse is only in 0.11 right? I modified the milestones under that assumption. If I’m wrong and you want to backport this, please change it back

**Comment by ilan-gold** [comment]
I don't think so, just the API to do i/o is

**Comment by flying-sheep** [comment]
OK, needs manual backport then

**Pull request merged**
